server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: adminsncesgi2022
    url: jdbc:mysql://socialnetcode.cpwcr46gx1dy.eu-west-1.rds.amazonaws.com:3306/social?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource

logging:
  level:
    root: info
    com.esgi.social: debug

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/doubao?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
#    type: com.zaxxer.hikari.HikariDataSource
#
#logging:
#  level:
#    root: info
#    com.douyuehan.doubao: info
